### ISSUE TITLE
Possible simplification

### ISSUE THREAD

**Issue by nicgirault** [jubbens/loopback-api-testing#1]
Hello,

Thank you for this simple librairy. It will simplify a lot of my tests. I am trying it right now.

In your example there is a need to specify the url "http://localhost:3000" but I think you could make it transparent for the developper since server.get('url') will return the url string.

Hope it helps

**Comment by jubbens** [comment]
Hi @nicgirault, thanks for the suggestion. If you want to make a PR I would be happy to review. :)
