### ISSUE TITLE
Cannot run tests, seems to be an internal issue: 1) "before all" hook   2) "after all" hook

### ISSUE THREAD

**Issue by amismailz** [jubbens/loopback-api-testing#10]
![screenshot from 2017-09-28 14-58-21](https://user-images.githubusercontent.com/9459819/30975624-ff91c120-a472-11e7-81d9-5fa3a409663c.png)

**Comment by jubbens** [comment]
I'm not sure from the title what the issue is. What is the expected behavior? What is the missing file start.sh?

**Comment by amismailz** [comment]
@jubbens I am so sorry that I uploaded a wrong attachment by mistake, I just updated it now.

**Comment by jubbens** [comment]
@amismailphp It looks like something is already listening on port 3000 so it can't lift the server. This is normal. Either free the port before testing, or if this is the server already running, you can alternatively pass null as the second argument so it doesn't try to lift the server before running the tests.
