### ISSUE TITLE
Boot scripts are not completed before api testing starts

### ISSUE THREAD

**Issue by dImrich** [jubbens/loopback-api-testing#8]
Hello,
My problem is that, api testing is started before my all boot scripts are done. Callbacks in boot scripts are fine.

**Comment by jubbens** [comment]
If you lift the server first before running the tests, does it work properly?

**Comment by dImrich** [comment]
I had async boot script with waterfall for automigrate + seeding tables. I've readed information about problems with automigrate in loopback boot scripts. It set booting variable to false before callback is called :/ I must to use separate script for migrating and seeding database before starting tests or server.

Sorry for my hurried issue. I tested your code and boot awaiting is OK.
